name: Satellite Ground Track Updater

on:
  schedule:
    - cron: '17 * * * *'  # Every hour at minute 17
  workflow_dispatch:      # Manual trigger

jobs:
  update-ground-tracks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify CSV presence
        run: |
          echo "Verifying sat_names.csv exists:"
          ls -l sat_names.csv

      - name: Run ground track updater
        env:
          SPACETRACK_USERNAME: ${{ secrets.SPACETRACK_USERNAME }}
          SPACETRACK_PASSWORD: ${{ secrets.SPACETRACK_PASSWORD }}
          AGOL_USERNAME: ${{ secrets.AGOL_USERNAME }}
          AGOL_PASSWORD: ${{ secrets.AGOL_PASSWORD }}
        run: |
          python src/update_ground_tracks.py

