name: Satellite Ground Track Updater

on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  update-ground-tracks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
          
      - name: Show Python version
        run: which python && python --version

      - name: Show Python version
        run: python --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Confirm CSV presence
        run: ls -la

      - name: Run ground track updater
        env:
          SPACETRACK_USERNAME: ${{ secrets.SPACETRACK_USERNAME }}
          SPACETRACK_PASSWORD: ${{ secrets.SPACETRACK_PASSWORD }}
          AGOL_USERNAME: ${{ secrets.AGOL_USERNAME }}
          AGOL_PASSWORD: ${{ secrets.AGOL_PASSWORD }}
        run: python src/update_ground_tracks.py

